[package]
name = "sinarust"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde-pickle = "1.1.1"
unicode-general-category = "1.0.0"
